### ISSUE TITLE
Crash `minimatch_1.default` is not a function

### ISSUE THREAD

**Issue by wooorm** [plantain-00/type-coverage#122]
#### Code(if relevant):

```
./node_modules/.bin/type-coverage
```

#### Expected:

Works fine :)

#### Actual:

```sh
$ ./node_modules/.bin/type-coverage
(0 , minimatch_1.default) is not a function
```

---

`type-coverage` just started failing today: https://github.com/wooorm/import-meta-resolve/pull/16/files. This PR does nothing with types, but the action is pulling in latest deps, which crashes.

So, seems something is up with minimatch:

```sh
$ npm ls minimatch
import-meta-resolve@3.0.0 /Users/tilde/Projects/oss/import-meta-resolve
├─┬ c8@7.13.0
│ ├─┬ rimraf@3.0.2
│ │ └─┬ glob@7.2.3
│ │   └── minimatch@3.1.2 deduped
│ └─┬ test-exclude@6.0.0
│   └── minimatch@3.1.2
├─┬ remark-cli@11.0.0
│ └─┬ unified-args@10.0.0
│   └─┬ unified-engine@10.1.0
│     ├─┬ glob@8.1.0
│     │ └── minimatch@5.1.6
│     └─┬ load-plugin@5.1.0
│       └─┬ @npmcli/config@6.1.6
│         └─┬ @npmcli/map-workspaces@3.0.4
│           ├─┬ glob@10.2.2
│           │ └── minimatch@9.0.0 deduped
│           └── minimatch@9.0.0
├─┬ type-coverage@2.25.1
│ └─┬ type-coverage-core@2.25.1
│   └── minimatch@3.1.2 deduped
└─┬ xo@0.54.2
  ├─┬ @eslint/eslintrc@1.4.1
  │ └── minimatch@3.1.2 deduped
  ├─┬ eslint-plugin-import@2.27.5
  │ └── minimatch@3.1.2 deduped
  ├─┬ eslint-plugin-n@15.7.0
  │ └── minimatch@3.1.2 deduped
  └─┬ eslint@8.39.0
    ├─┬ @eslint/eslintrc@2.0.2
    │ └── minimatch@3.1.2 deduped
    ├─┬ @humanwhocodes/config-array@0.11.8
    │ └── minimatch@3.1.2 deduped
    └── minimatch@3.1.2 deduped
```

I guess `type-coverage` is importing `minimatch` 9 somehow? It looks like minimatch 9 (3 weeks ago) removed the default export: https://github.com/isaacs/minimatch/blob/main/changelog.md.

**Comment by ribeaud** [comment]
Mmmmh... Does not solve the problem on my side. But I am actually unsure whether the problem is related to `type-coverage`:
```
> npm ls minimatch
biomedit-portal-frontend@5.3.1-dev.7 /Users/christianr/Documents/workspace/portal/frontend
├─┬ @next/eslint-plugin-next@13.3.4
│ └─┬ glob@7.1.7
│   └── minimatch@3.1.2 deduped
├─┬ @openapitools/openapi-generator-cli@2.6.0
│ └─┬ glob@7.1.6
│   └── minimatch@3.1.2 deduped
├─┬ depcheck@1.4.3
│ ├── minimatch@3.1.2
│ └─┬ multimatch@5.0.0
│   └── minimatch@3.1.2 deduped
├─┬ dpdm@3.13.0
│ └─┬ glob@9.3.5
│   └── minimatch@8.0.4
├─┬ eslint-plugin-react@7.32.2
│ └── minimatch@3.1.2 deduped
├─┬ eslint@8.40.0
│ ├─┬ @eslint/eslintrc@2.0.3
│ │ └── minimatch@3.1.2 deduped
│ ├─┬ @humanwhocodes/config-array@0.11.8
│ │ └── minimatch@3.1.2 deduped
│ └── minimatch@3.1.2 deduped
├─┬ jest@29.5.0
│ └─┬ @jest/core@29.5.0
│   └─┬ @jest/transform@29.5.0
│     └─┬ babel-plugin-istanbul@6.1.1
│       └─┬ test-exclude@6.0.0
│         └── minimatch@3.1.2 deduped
├─┬ npm-run-all@4.1.5
│ └── minimatch@3.1.2 deduped
├─┬ rimraf@5.0.0
│ └─┬ glob@10.2.2
│   └── minimatch@9.0.0
└─┬ type-coverage@2.25.2
  └─┬ type-coverage-core@2.25.2
    └── minimatch@3.1.2 deduped
```
But I came across this issue and I thought, I might find some help here. The problematic `MR` is [here](https://gitlab.com/biomedit/portal/-/merge_requests/752).

I found out that if I remove `--ignore-files` from the invocation, the command is successful. If we have a look at my dependencies tree, we see that `minimatch@9.0.0` will be installed for **glob**. Could that be the problem?

**Comment by plantain-00** [comment]
@ribeaud v2.25.3 should fix this

**Comment by ribeaud** [comment]
I actually did. Thank you! 💪

**Comment by wooorm** [comment]
think this can be closed?

**Comment by simoneguzzi** [comment]
Hi All! 👋 

After upgrading to v2.29.6, I experience a similar issue, but with `normalize-path`:

```shell
❯ node_modules/.bin/type-coverage -p tsconfig.json --strict
(0 , normalize_path_1.default) is not a function
```

Could [this change](https://github.com/plantain-00/type-coverage/commit/2ac5cf21eb6f1524a7dc5f89e9840081869fc72a#diff-b433c5c07c8127b1e0f39ad26c38ab538fd43638a064678174f2ba3c27b62e47R5) be related?

**Comment by wooorm** [comment]
I had forgotten about this issue but I just had many builds fail as well. https://github.com/wooorm/wooorm.github.io/actions/runs/11341385777, https://github.com/unifiedjs/github-tools/actions/runs/11341624394, https://github.com/unifiedjs/npm-tools/actions/runs/11341980179.

So, while I think this was fixed, perhaps it was re-introduced somehow?

**Comment by plantain-00** [comment]
> Hi All! 👋
> 
> After upgrading to v2.29.6, I experience a similar issue, but with `normalize-path`:
> 
> ```shell
> ❯ node_modules/.bin/type-coverage -p tsconfig.json --strict
> (0 , normalize_path_1.default) is not a function
> ```
> 
> Could [this change](https://github.com/plantain-00/type-coverage/commit/2ac5cf21eb6f1524a7dc5f89e9840081869fc72a#diff-b433c5c07c8127b1e0f39ad26c38ab538fd43638a064678174f2ba3c27b62e47R5) be related?

Seems so, I will revert it in v2.29.7

**Comment by simoneguzzi** [comment]
> It should be OK now.

Can confirm. Thanks for the timely fix ❤️
